name = "key-system-worker"
main = "index.js"
compatibility_date = "2024-01-01"

# Выбери режим деплоя
[env.production]

# Дублируем секрет здесь (опционально)
vars = { API_SECRET = "vernamontop" }

# Если используешь Cloudflare KV (для хранения ключей)
# [kv_namespaces]
# binding = "KEY_STORE"
# id = "your-kv-id"
